### ISSUE TITLE
What happened to version 3.0?

### ISSUE THREAD

**Issue by kgreed** [SvenGroot/ookii.commandline#2]
Hello Sven
I really want to use version 3.0 which is referenced by the solution at [Delegate]
(http://blog.delegate.at/2016/02/26/nuget-packages-devexpress-components.html)
It is important to me so that I can get DevExpress Xaf Mobile solutions building in Azure DevOps
Do you know where I can find it please?

**Comment by Thieum** [comment]
See https://github.com/biohazard999/DXNugetPackageBuilder/issues/3#issuecomment-415118385 - I created the version 3.0 and hoped for the maintainer of ooki.commandline to pull the changes, but got no answer so far.
See also my branch, if you want to build the nuget from there: https://github.com/Thieum/ookii.commandline/tree/netstandard

**Comment by Thieum** [comment]
@kgreed @SvenGroot this can be closed.
